trigger:
  - main

parameters:
  - name: targetEnvironment
    displayName: "Select Deployment Environment"
    type: string
    default: sandbox
    values:
      - sandbox
      - production
  - name: deploymentType
    displayName: "Deployment Type"
    type: string
    default: data
    values:
      - data
      - metadata
  - name: sObjectName
    displayName: "SObject Name (for data deployment)"
    type: string
    default: Account
  - name: externalIdField
    displayName: "External ID Field (for data deployment)"
    type: string
    default: External_Id__c
  - name: sourcePath
    displayName: "Source Path (for metadata deployment)"
    type: string
    default: force-app

variables:
  - name: loginUrl
    ${{ if eq(parameters.targetEnvironment, 'production') }}:
      value: 'https://login.salesforce.com'
    ${{ else }}:
      value: 'https://test.salesforce.com'

stages:
  - stage: DeployToSalesforce
    displayName: "Deploy to Salesforce"
    jobs:
      - job: SalesforceDeployment
        displayName: "Salesforce Deployment"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              echo "Installing Salesforce CLI..."
              npm install sfdx-cli --global
            displayName: 'Install Salesforce CLI'

          - script: |
              echo "Authenticating to Salesforce using device login on URL: $(loginUrl)"
              sfdx force:auth:device:login -r $(loginUrl) --setdefaultusername
            displayName: 'Salesforce Device Login'

          # --- Data Deployment Steps ---
          - ${{ if eq(parameters.deploymentType, 'data') }}:
            - script: |
                echo "Installing Node.js dependencies for data deployment..."
                npm install json2csv
              displayName: 'Install JSON to CSV Converter Dependencies'
            - script: |
                echo "Converting JSON to CSV..."
                node convertJsonToCsv.js
              displayName: 'Convert JSON to CSV'
            - script: |
                echo "Deploying data to Salesforce..."
                sfdx force:data:bulk:upsert -s ${{ parameters.sObjectName }} -f output.csv -i ${{ parameters.externalIdField }} --wait 10
              displayName: 'Deploy Data to Salesforce'

          # --- Metadata Deployment Steps ---
          - ${{ if and(eq(parameters.deploymentType, 'metadata'), eq(parameters.targetEnvironment, 'production')) }}:
            - script: |
                echo "Deploying metadata to Salesforce with test execution..."
                sfdx force:source:deploy -p ${{ parameters.sourcePath }} --testlevel RunLocalTests
              displayName: 'Deploy Metadata to Salesforce (RunLocalTests)'
          - ${{ if and(eq(parameters.deploymentType, 'metadata'), ne(parameters.targetEnvironment, 'production')) }}:
            - script: |
                echo "Deploying metadata to Salesforce without running tests..."
                sfdx force:source:deploy -p ${{ parameters.sourcePath }} --testlevel NoTestRun
              displayName: 'Deploy Metadata to Salesforce (NoTestRun)'
